package com.frame.ssh.dao;
// Generated 2013-3-13 17:30:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * HhJobApply generated by hbm2java
 */
public class HhJobApply implements java.io.Serializable {

	private Integer hhJobApplyId;
	private HhJob hhJob;
	private Integer hhUserId;
	private Integer hhJobSeekerId;
	private String name;
	private String email;
	private String mobile;
	private String phone;
	private String resumeName;
	private char applyType; // ENUM(T,H,S). 申请类型，T-Trusteeship, H-Headhunting, S-Job Seeker.
	private BigDecimal payPercent;
	private String currentStep;
	private char status; // ENUM(O,S,R,C). 申请状态，O-open, S-success, R-reject, C-Cancel.
	private String referenceReport;
	private String offerLetter;
	private Integer offeredAnnualPay; // 实际年薪.
	private Integer finalPay; // 最终佣金.
	private Integer finalPayForUser; // 最终付给猎头或托管者的佣金.
	private String remarkInternal;
	private Date checkpoint;
	private char contactInfoOpenLevel; // ENUM(H,O). 候选人联系信息公开级别，H-hidden for HR, O-open for HR after approved.
	private Date updateTime;
	private Date createTime;

	public HhJobApply() {
	}

	public HhJobApply(HhJob hhJob, char applyType, BigDecimal payPercent, String currentStep, char status,
			char contactInfoOpenLevel, Date updateTime, Date createTime) {
		this.hhJob = hhJob;
		this.applyType = applyType;
		this.payPercent = payPercent;
		this.currentStep = currentStep;
		this.status = status;
		this.contactInfoOpenLevel = contactInfoOpenLevel;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}
	public HhJobApply(HhJob hhJob, Integer hhUserId, Integer hhJobSeekerId, String name, String email, String mobile,
			String phone, String resumeName, char applyType, BigDecimal payPercent, String currentStep, char status,
			String referenceReport, String offerLetter, Integer offeredAnnualPay, Integer finalPay,
			Integer finalPayForUser, String remarkInternal, Date checkpoint, char contactInfoOpenLevel,
			Date updateTime, Date createTime) {
		this.hhJob = hhJob;
		this.hhUserId = hhUserId;
		this.hhJobSeekerId = hhJobSeekerId;
		this.name = name;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.resumeName = resumeName;
		this.applyType = applyType;
		this.payPercent = payPercent;
		this.currentStep = currentStep;
		this.status = status;
		this.referenceReport = referenceReport;
		this.offerLetter = offerLetter;
		this.offeredAnnualPay = offeredAnnualPay;
		this.finalPay = finalPay;
		this.finalPayForUser = finalPayForUser;
		this.remarkInternal = remarkInternal;
		this.checkpoint = checkpoint;
		this.contactInfoOpenLevel = contactInfoOpenLevel;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	public Integer getHhJobApplyId() {
		return this.hhJobApplyId;
	}

	public void setHhJobApplyId(Integer hhJobApplyId) {
		this.hhJobApplyId = hhJobApplyId;
	}
	public HhJob getHhJob() {
		return this.hhJob;
	}

	public void setHhJob(HhJob hhJob) {
		this.hhJob = hhJob;
	}
	public Integer getHhUserId() {
		return this.hhUserId;
	}

	public void setHhUserId(Integer hhUserId) {
		this.hhUserId = hhUserId;
	}
	public Integer getHhJobSeekerId() {
		return this.hhJobSeekerId;
	}

	public void setHhJobSeekerId(Integer hhJobSeekerId) {
		this.hhJobSeekerId = hhJobSeekerId;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getResumeName() {
		return this.resumeName;
	}

	public void setResumeName(String resumeName) {
		this.resumeName = resumeName;
	}
	public char getApplyType() {
		return this.applyType;
	}

	public void setApplyType(char applyType) {
		this.applyType = applyType;
	}
	public BigDecimal getPayPercent() {
		return this.payPercent;
	}

	public void setPayPercent(BigDecimal payPercent) {
		this.payPercent = payPercent;
	}
	public String getCurrentStep() {
		return this.currentStep;
	}

	public void setCurrentStep(String currentStep) {
		this.currentStep = currentStep;
	}
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}
	public String getReferenceReport() {
		return this.referenceReport;
	}

	public void setReferenceReport(String referenceReport) {
		this.referenceReport = referenceReport;
	}
	public String getOfferLetter() {
		return this.offerLetter;
	}

	public void setOfferLetter(String offerLetter) {
		this.offerLetter = offerLetter;
	}
	public Integer getOfferedAnnualPay() {
		return this.offeredAnnualPay;
	}

	public void setOfferedAnnualPay(Integer offeredAnnualPay) {
		this.offeredAnnualPay = offeredAnnualPay;
	}
	public Integer getFinalPay() {
		return this.finalPay;
	}

	public void setFinalPay(Integer finalPay) {
		this.finalPay = finalPay;
	}
	public Integer getFinalPayForUser() {
		return this.finalPayForUser;
	}

	public void setFinalPayForUser(Integer finalPayForUser) {
		this.finalPayForUser = finalPayForUser;
	}
	public String getRemarkInternal() {
		return this.remarkInternal;
	}

	public void setRemarkInternal(String remarkInternal) {
		this.remarkInternal = remarkInternal;
	}
	public Date getCheckpoint() {
		return this.checkpoint;
	}

	public void setCheckpoint(Date checkpoint) {
		this.checkpoint = checkpoint;
	}
	public char getContactInfoOpenLevel() {
		return this.contactInfoOpenLevel;
	}

	public void setContactInfoOpenLevel(char contactInfoOpenLevel) {
		this.contactInfoOpenLevel = contactInfoOpenLevel;
	}
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public static enum applyType {
		T, H, S;
	}
	public static enum status {
		O, S, R, C;
	}
	public static enum contactInfoOpenLevel {
		H, O;
	}

	public static enum FieldNamesEnum {
		hhJob, hhUserId, hhJobSeekerId, name, email, mobile, phone, resumeName, applyType, payPercent, currentStep, status, referenceReport, offerLetter, offeredAnnualPay, finalPay, finalPayForUser, remarkInternal, checkpoint, contactInfoOpenLevel, updateTime, createTime;
	}

}
